from .ages import *
from .customers import *
from .emails import *
from .education_ocupation import *
from .emails import *
from .genders import *
from .health import *
from .housing import *
from .legacy_names import *
from .locations import *
from .passwords import *
from .phones import *